project_id = "yyzcgxnvtprojutnxisz"

[functions.social-sync]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false

[functions.subscription-reminder]
verify_jwt = false
