project_id = "yyzcgxnvtprojutnxisz"

[functions.social-sync]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false

[functions.subscription-reminder]
verify_jwt = false

[functions.momo-chat]
verify_jwt = false

[functions.entitlements-me]
verify_jwt = true

[functions.entitlements-lookup]
verify_jwt = false

[functions.check-entitlement]
verify_jwt = false

[functions.external-api]
verify_jwt = true
